#!/bin/bash

echo "🌊 Binary Waterfall CLI - Quick Demo"
echo "===================================="
echo ""
echo "The binary is built and ready at: ./bwfall"
echo ""
echo "Quick tests you can run:"
echo ""
echo "1. Visual waterfall (safe, no audio):"
echo "   ./bwfall --no-audio /bin/ls"
echo ""
echo "2. Matrix style:"
echo "   ./bwfall --no-audio --visual-mode matrix /bin/bash"
echo ""
echo "3. Hex dump:"
echo "   ./bwfall --no-audio --visual-mode hex /bin/ls"
echo ""
echo "4. With audio (if ALSA works):"
echo "   ./bwfall /bin/ls"
echo ""
echo "5. Random data stream:"
echo "   cat /dev/urandom | ./bwfall --no-audio --speed 0.5"
echo ""
echo "Press Ctrl+C to stop any running demo"
echo ""
echo "Ready to test? Try this command:"
echo "./bwfall --no-audio --visual-mode matrix --speed 0.5 /bin/bash"
